name: .NET Format

on:
  push:
    branches:
      - develop
  pull_request:
    branches-ignore:
      - main

jobs:
  dotnet-format:
    if: "!contains(github.event.head_commit.message, '.NET Format Style Fixes')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BYPASS_WORKFLOW_PAT }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Restore Tool Dependencies
        run: dotnet tool install -g csharpier

      - name: CSharpier Format
        run: csharpier format .

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: .NET Format Style Fixes
          commit_user_name: Format Bot
